/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.*;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author longnh
 */
public class AddCouponFrm extends javax.swing.JFrame {
    
    private final int UNKNOWN_COUPON = -1;
    private final int USED_COUPON = -2;
    private final int EXPIRED_COUPON = -3;
    
    private Controller controller;
    /**
     * Creates new form AddCouponFrm
     */
    public AddCouponFrm(Controller controller) {
        initComponents();
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        coupon_input = new javax.swing.JTextField();
        confirm_coupon_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Mã giảm giá:");

        confirm_coupon_btn.setText("Xác nhận");
        confirm_coupon_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_coupon_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(coupon_input, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(confirm_coupon_btn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(coupon_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirm_coupon_btn))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirm_coupon_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_coupon_btnActionPerformed
        System.out.println(evt.getActionCommand());
        String coupon = this.coupon_input.getText();
        if(validate_coupon(coupon) == true){
            int result = this.controller.apply_coupon_to_bill(coupon);
            if(result == USED_COUPON){
                JOptionPane.showMessageDialog(null, "Mã giảm giá đã được sử dụng!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else if(result == EXPIRED_COUPON){
                JOptionPane.showMessageDialog(null, "Mã giảm giá đã hết thời hạn sử dụng!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else if(result == UNKNOWN_COUPON){
                JOptionPane.showMessageDialog(null, "Mã giảm giá không tồn tại trong cơ sở dữ liệu!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_confirm_coupon_btnActionPerformed

    private boolean validate_coupon(String coupon){
        if(coupon.equals("")){
            JOptionPane.showMessageDialog(null, "Chưa nhập mã giảm giá", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        } else{
            final String standard_coupon_pattern = "^[a-zA-Z0-9]*$";
            Pattern p = Pattern.compile(standard_coupon_pattern);
            Matcher m = p.matcher(coupon);
            if(!m.find()){
                JOptionPane.showMessageDialog(null, "Mã giảm giá chứa ký tự đặc biệt! Không hợp lệ", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirm_coupon_btn;
    private javax.swing.JTextField coupon_input;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
